export interface Flashcard {
  id: string;
  category: string;
  front: string;
  back: string;
  code?: string;
  difficulty: "beginner" | "intermediate" | "advanced";
}

export const flashcardData: Flashcard[] = [
  // Variables & Types
  { id: "v1", category: "Variables & Types", front: "What is the difference between `var`, `let`, and `const`?", back: "`var` is function-scoped and hoisted. `let` is block-scoped, not hoisted to the top. `const` is block-scoped, not hoisted, and cannot be reassigned (but objects/arrays can be mutated).", code: "var x = 1; // function-scoped\nlet y = 2; // block-scoped\nconst z = 3; // block-scoped, no reassign\n\n// const objects CAN be mutated\nconst obj = { a: 1 };\nobj.a = 2; // OK", difficulty: "beginner" },
  { id: "v2", category: "Variables & Types", front: "What are the 7 primitive types in JavaScript?", back: "string, number, bigint, boolean, undefined, null, and symbol. Everything else is an object (including arrays, functions, and dates).", code: "typeof 'hello'   // 'string'\ntypeof 42        // 'number'\ntypeof 42n       // 'bigint'\ntypeof true      // 'boolean'\ntypeof undefined // 'undefined'\ntypeof null      // 'object' (bug!)\ntypeof Symbol()  // 'symbol'", difficulty: "beginner" },
  { id: "v3", category: "Variables & Types", front: "What is type coercion?", back: "JavaScript automatically converts values between types. This can lead to surprising results. Use `===` (strict equality) to avoid coercion.", code: "'5' + 3     // '53' (string concat)\n'5' - 3     // 2 (numeric)\n'5' == 5    // true (coercion)\n'5' === 5   // false (strict)\n!!'hello'   // true (truthy)\n!!0         // false (falsy)", difficulty: "beginner" },

  // Functions
  { id: "f1", category: "Functions", front: "What is the difference between function declarations and expressions?", back: "Declarations are hoisted (can be called before defined). Expressions are not hoisted. Arrow functions don't have their own `this`.", code: "// Declaration (hoisted)\nconsole.log(add(1, 2)); // 3\nfunction add(a, b) { return a + b; }\n\n// Expression (not hoisted)\nconst multiply = function(a, b) { return a * b; };\n\n// Arrow function (no own 'this')\nconst double = x => x * 2;", difficulty: "beginner" },
  { id: "f2", category: "Functions", front: "What is a closure?", back: "A closure is a function that retains access to variables from its outer scope, even after the outer function has returned. This enables data privacy and stateful functions.", code: "function createCounter() {\n  let count = 0; // enclosed variable\n  return {\n    increment: () => ++count,\n    getCount: () => count,\n  };\n}\n\nconst counter = createCounter();\ncounter.increment(); // 1\ncounter.increment(); // 2\ncounter.getCount(); // 2", difficulty: "intermediate" },
  { id: "f3", category: "Functions", front: "What is the difference between `call`, `apply`, and `bind`?", back: "`call` invokes a function with a specific `this` and individual arguments. `apply` is the same but takes an array of arguments. `bind` returns a new function with `this` permanently bound.", code: "function greet(greeting) {\n  return `${greeting}, ${this.name}`;\n}\n\nconst user = { name: 'Alice' };\n\ngreet.call(user, 'Hello');     // 'Hello, Alice'\ngreet.apply(user, ['Hi']);    // 'Hi, Alice'\nconst bound = greet.bind(user);\nbound('Hey');                   // 'Hey, Alice'", difficulty: "intermediate" },
  { id: "f4", category: "Functions", front: "What are default parameters and rest parameters?", back: "Default parameters let you set fallback values. Rest parameters (`...args`) collect all remaining arguments into an array.", code: "function greet(name = 'World', ...extras) {\n  console.log(`Hello, ${name}!`);\n  console.log('Extras:', extras);\n}\n\ngreet();                 // 'Hello, World!'\ngreet('Alice');           // 'Hello, Alice!'\ngreet('Bob', 1, 2, 3);  // Extras: [1, 2, 3]", difficulty: "beginner" },

  // Arrays
  { id: "a1", category: "Arrays", front: "What is the difference between `map`, `filter`, and `reduce`?", back: "`map` transforms each element and returns a new array. `filter` keeps elements that pass a test. `reduce` accumulates all elements into a single value.", code: "const nums = [1, 2, 3, 4, 5];\n\nnums.map(n => n * 2);       // [2, 4, 6, 8, 10]\nnums.filter(n => n > 2);   // [3, 4, 5]\nnums.reduce((sum, n) => sum + n, 0); // 15", difficulty: "beginner" },
  { id: "a2", category: "Arrays", front: "What is array destructuring?", back: "Destructuring lets you unpack values from arrays into variables. You can skip elements, use defaults, and swap variables.", code: "const [a, b, c] = [1, 2, 3];\nconst [first, , third] = [10, 20, 30]; // first=10, third=30\nconst [x, y = 5] = [1]; // x=1, y=5\n\n// Swap variables\nlet p = 1, q = 2;\n[p, q] = [q, p]; // p=2, q=1", difficulty: "beginner" },
  { id: "a3", category: "Arrays", front: "What does `Array.isArray()` do and why is it better than `typeof`?", back: "`typeof []` returns `'object'` because arrays are objects. `Array.isArray([])` correctly returns `true`.", code: "typeof []           // 'object' (wrong!)\ntypeof {}           // 'object'\nArray.isArray([])   // true\nArray.isArray({})   // false\n\n// The only reliable way to check for arrays", difficulty: "beginner" },
  { id: "a4", category: "Arrays", front: "What are `some` and `every`?", back: "`some` returns true if at least one element passes the test. `every` returns true only if ALL elements pass.", code: "const nums = [1, 2, 3, 4, 5];\n\nnums.some(n => n > 4);   // true (5 > 4)\nnums.every(n => n > 0);  // true (all positive)\nnums.every(n => n > 2);  // false (1 is not > 2)", difficulty: "beginner" },

  // Objects
  { id: "o1", category: "Objects", front: "What is object destructuring?", back: "Unpacks properties from objects into variables. Supports renaming, defaults, and nested destructuring.", code: "const user = { name: 'Alice', age: 25, city: 'NYC' };\n\nconst { name, age } = user;\nconst { name: userName, role = 'user' } = user;\n\n// Nested\nconst { address: { zip } } = {\n  address: { zip: '10001' }\n};", difficulty: "beginner" },
  { id: "o2", category: "Objects", front: "What is the spread operator for objects?", back: "Creates shallow copies and merges objects. Later properties override earlier ones.", code: "const defaults = { theme: 'dark', lang: 'en' };\nconst userPrefs = { theme: 'light', fontSize: 16 };\n\nconst config = { ...defaults, ...userPrefs };\n// { theme: 'light', lang: 'en', fontSize: 16 }\n\n// Shallow clone\nconst clone = { ...original };", difficulty: "beginner" },
  { id: "o3", category: "Objects", front: "What are `Object.keys`, `Object.values`, and `Object.entries`?", back: "Keys returns an array of property names. Values returns an array of values. Entries returns [key, value] pairs.", code: "const user = { name: 'Alice', age: 25 };\n\nObject.keys(user);   // ['name', 'age']\nObject.values(user); // ['Alice', 25]\nObject.entries(user); // [['name','Alice'], ['age',25]]\n\n// Iterate with entries\nObject.entries(user).forEach(([key, val]) => {\n  console.log(`${key}: ${val}`);\n});", difficulty: "beginner" },
  { id: "o4", category: "Objects", front: "What is the difference between `Object.freeze` and `Object.seal`?", back: "`freeze` makes an object completely immutable (no add, delete, or modify). `seal` prevents adding/deleting properties but allows modifying existing ones.", code: "const frozen = Object.freeze({ a: 1 });\nfrozen.a = 2;     // fails silently (strict: error)\nfrozen.b = 3;     // fails\n\nconst sealed = Object.seal({ a: 1 });\nsealed.a = 2;     // OK - can modify\nsealed.b = 3;     // fails - can't add", difficulty: "intermediate" },

  // DOM
  { id: "d1", category: "DOM", front: "What is the difference between `textContent`, `innerText`, and `innerHTML`?", back: "`textContent` gets all text including hidden. `innerText` gets only visible text (triggers reflow). `innerHTML` gets/sets HTML markup as a string.", code: "// textContent - raw text, fast\nel.textContent = 'Hello';\n\n// innerHTML - parses HTML\nel.innerHTML = '<strong>Hello</strong>';\n\n// innerText - visible text only, slower\nel.innerText = 'Hello';", difficulty: "beginner" },
  { id: "d2", category: "DOM", front: "What is event delegation?", back: "Attaching a single event listener to a parent element instead of individual listeners on children. Events bubble up, and you check `event.target`.", code: "// Instead of:\ndocument.querySelectorAll('.item').forEach(el => {\n  el.addEventListener('click', handleClick);\n});\n\n// Use delegation:\ndocument.querySelector('.list').addEventListener(\n  'click', (e) => {\n    if (e.target.matches('.item')) {\n      handleClick(e);\n    }\n  }\n);", difficulty: "intermediate" },
  { id: "d3", category: "DOM", front: "What is `addEventListener`'s third argument?", back: "It's an options object (or boolean for `useCapture`). Key options: `once` (auto-remove), `passive` (won't call preventDefault), `capture` (listen in capture phase).", code: "el.addEventListener('click', handler, {\n  once: true,    // auto-remove after first call\n  passive: true, // promises not to call preventDefault\n  capture: false // listen in bubble phase (default)\n});", difficulty: "intermediate" },

  // Async
  { id: "as1", category: "Async", front: "What is the Event Loop?", back: "The event loop continuously checks if the call stack is empty. If so, it moves the next callback from the microtask queue (Promises) or callback queue (setTimeout) onto the stack.", difficulty: "intermediate" },
  { id: "as2", category: "Async", front: "What is the difference between `setTimeout(fn, 0)` and `Promise.resolve().then(fn)`?", back: "Promises (microtasks) always execute before setTimeout callbacks (macrotasks). Microtasks have higher priority in the event loop.", code: "console.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nconsole.log('4');\n// Output: 1, 4, 3, 2", difficulty: "intermediate" },
  { id: "as3", category: "Async", front: "What does `async/await` do?", back: "`async` makes a function return a Promise. `await` pauses execution until the Promise resolves. It makes async code look synchronous.", code: "async function fetchUser(id) {\n  try {\n    const res = await fetch(`/api/users/${id}`);\n    const user = await res.json();\n    return user;\n  } catch (err) {\n    console.error('Failed:', err);\n  }\n}", difficulty: "beginner" },
  { id: "as4", category: "Async", front: "What are Promise.all, Promise.race, Promise.allSettled, and Promise.any?", back: "`all` waits for all to resolve (fails on first rejection). `race` returns first to settle. `allSettled` waits for all with results. `any` returns first fulfilled.", code: "const p1 = Promise.resolve(1);\nconst p2 = Promise.reject('err');\nconst p3 = Promise.resolve(3);\n\nPromise.allSettled([p1, p2, p3]);\n// [{status:'fulfilled',value:1},\n//  {status:'rejected',reason:'err'},\n//  {status:'fulfilled',value:3}]", difficulty: "intermediate" },

  // ES6+
  { id: "e1", category: "ES6+", front: "What is optional chaining (`?.`)?", back: "Safely accesses nested properties. Returns `undefined` instead of throwing if a link in the chain is null/undefined.", code: "const user = { address: { zip: '10001' } };\n\nuser?.address?.zip     // '10001'\nuser?.phone?.number    // undefined\nuser?.getName?.()      // undefined if no getName\n\n// vs without optional chaining:\n// user && user.address && user.address.zip", difficulty: "beginner" },
  { id: "e2", category: "ES6+", front: "What is nullish coalescing (`??`)?", back: "Returns the right operand when the left is `null` or `undefined` only. Unlike `||`, it doesn't treat 0, '', or false as falsy.", code: "const count = 0;\ncount || 10   // 10 (0 is falsy)\ncount ?? 10   // 0 (0 is not null/undefined)\n\nconst name = '';\nname || 'Anon'  // 'Anon' ('' is falsy)\nname ?? 'Anon'  // '' ('' is not null/undefined)", difficulty: "beginner" },
  { id: "e3", category: "ES6+", front: "What are template literals?", back: "String literals with backticks that support embedded expressions via `${}`, multi-line strings, and tagged templates.", code: "const name = 'World';\nconst greeting = `Hello, ${name}!`;\n\nconst html = `\n  <div class=\"card\">\n    <h2>${greeting}</h2>\n    <p>Today: ${new Date().toLocaleDateString()}</p>\n  </div>\n`;", difficulty: "beginner" },
  { id: "e4", category: "ES6+", front: "What are Symbols and what are they used for?", back: "Symbols create unique, immutable identifiers. Used for object property keys that won't collide, and for well-known symbols like `Symbol.iterator`.", code: "const id = Symbol('unique');\nconst obj = { [id]: 42, name: 'test' };\nobj[id]; // 42\nObject.keys(obj); // ['name'] - symbol keys hidden\n\n// Well-known symbols\nconst arr = [1, 2, 3];\narr[Symbol.iterator]; // the iterator function", difficulty: "advanced" },

  // OOP
  { id: "oop1", category: "OOP", front: "What are classes in JavaScript?", back: "Classes are syntactic sugar over prototypal inheritance. They provide a cleaner syntax for creating objects and handling inheritance.", code: "class Animal {\n  constructor(name) {\n    this.name = name;\n  }\n  speak() {\n    return `${this.name} makes a sound.`;\n  }\n}\n\nclass Dog extends Animal {\n  speak() {\n    return `${this.name} barks!`;\n  }\n}\n\nnew Dog('Rex').speak(); // 'Rex barks!'", difficulty: "beginner" },
  { id: "oop2", category: "OOP", front: "What are getters and setters?", back: "Special methods that run when getting or setting a property. They allow computed properties and validation.", code: "class User {\n  #_name;\n  get name() { return this.#_name.toUpperCase(); }\n  set name(val) {\n    if (val.length < 2) throw new Error('Too short');\n    this.#_name = val;\n  }\n}\n\nconst u = new User();\nu.name = 'alice'; // calls setter\nconsole.log(u.name); // 'ALICE' - calls getter", difficulty: "intermediate" },
  { id: "oop3", category: "OOP", front: "What are private class fields?", back: "Fields prefixed with `#` are truly private - they cannot be accessed outside the class body.", code: "class BankAccount {\n  #balance = 0;\n\n  deposit(amount) {\n    if (amount > 0) this.#balance += amount;\n  }\n  getBalance() {\n    return this.#balance;\n  }\n}\n\nconst acc = new BankAccount();\nacc.#balance; // SyntaxError!\nacc.deposit(100);\nacc.getBalance(); // 100", difficulty: "intermediate" },
  { id: "oop4", category: "OOP", front: "What is `static` in a class?", back: "Static methods/properties belong to the class itself, not instances. Called on the class, not on `this`.", code: "class MathHelper {\n  static PI = 3.14159;\n  static add(a, b) { return a + b; }\n  static multiply(a, b) { return a * b; }\n}\n\nMathHelper.add(2, 3);    // 5\nMathHelper.PI;            // 3.14159\n\n// const m = new MathHelper();\n// m.add(2, 3); // TypeError!", difficulty: "beginner" },

  // Errors
  { id: "err1", category: "Errors", front: "What are the error types in JavaScript?", back: "Error (generic), SyntaxError (parsing), TypeError (wrong type), ReferenceError (undeclared variable), RangeError (out of range), URIError (malformed URI).", difficulty: "beginner" },
  { id: "err2", category: "Errors", front: "How does try/catch/finally work?", back: "`try` runs code that might throw. `catch` handles the error. `finally` always runs (cleanup).", code: "try {\n  const data = JSON.parse('invalid');\n} catch (err) {\n  console.error('Parse failed:', err.message);\n} finally {\n  console.log('This always runs');\n}\n// Output:\n// Parse failed: Unexpected token...\n// This always runs", difficulty: "beginner" },
  { id: "err3", category: "Errors", front: "How do you create custom errors?", back: "Extend the Error class to create domain-specific error types with custom properties.", code: "class ValidationError extends Error {\n  constructor(field, message) {\n    super(message);\n    this.name = 'ValidationError';\n    this.field = field;\n  }\n}\n\ntry {\n  throw new ValidationError('email', 'Invalid email');\n} catch (err) {\n  if (err instanceof ValidationError) {\n    console.log(err.field); // 'email'\n  }\n}", difficulty: "intermediate" },

  // Patterns
  { id: "p1", category: "Patterns", front: "What is the Module Pattern?", back: "Uses closures to create private state and expose a public API. Common in ES5 before ES6 modules.", code: "const Counter = (function() {\n  let count = 0; // private\n  return {\n    increment: () => ++count,\n    decrement: () => --count,\n    getCount: () => count,\n  };\n})();\n\nCounter.increment();\nCounter.getCount(); // 1", difficulty: "intermediate" },
  { id: "p2", category: "Patterns", front: "What is the Observer/Pub-Sub Pattern?", back: "Objects (subjects) notify other objects (observers) when their state changes. Decouples producers from consumers.", code: "class EventEmitter {\n  #handlers = {};\n  on(event, fn) {\n    (this.#handlers[event] ??= []).push(fn);\n  }\n  emit(event, ...args) {\n    (this.#handlers[event] || []).forEach(fn => fn(...args));\n  }\n}\n\nconst bus = new EventEmitter();\nbus.on('data', d => console.log(d));\nbus.emit('data', 'hello'); // 'hello'", difficulty: "advanced" },
  { id: "p3", category: "Patterns", front: "What is memoization?", back: "Caching function results to avoid redundant computations. Stores previous results keyed by arguments.", code: "function memoize(fn) {\n  const cache = new Map();\n  return (...args) => {\n    const key = JSON.stringify(args);\n    if (cache.has(key)) return cache.get(key);\n    const result = fn(...args);\n    cache.set(key, result);\n    return result;\n  };\n}\n\nconst factorial = memoize(n =>\n  n <= 1 ? 1 : n * factorial(n - 1)\n);", difficulty: "advanced" },
  { id: "p4", category: "Patterns", front: "What is a debounce function?", back: "Delays executing a function until after a period of inactivity. Useful for search inputs, resize handlers, and scroll events.", code: "function debounce(fn, delay) {\n  let timer;\n  return (...args) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), delay);\n  };\n}\n\nconst search = debounce(query => {\n  fetchResults(query);\n}, 300);\n\ninput.addEventListener('input', e => search(e.target.value));", difficulty: "advanced" },
];