export interface Project {
  id: string;
  title: string;
  description: string;
  difficulty: "beginner" | "intermediate" | "advanced" | "expert";
  category: string;
  duration: string;
  skills: string[];
  steps: string[];
  codePreview?: string;
}

export const projectData: Project[] = [
  {
    id: "proj-1",
    title: "Calculator App",
    description: "Build a fully functional calculator with basic arithmetic operations, clear, and a beautiful UI.",
    difficulty: "beginner",
    category: "Utility",
    duration: "2 hours",
    skills: ["Variables", "Functions", "DOM Manipulation", "Events", "CSS"],
    steps: [
      "Create the HTML structure with display and buttons",
      "Style the calculator with CSS grid",
      "Implement number and operator input",
      "Build the calculation logic",
      "Add keyboard support and error handling",
    ],
    codePreview: `// Calculator logic\nlet display = document.getElementById('display');\nlet current = '0';\nlet operator = null;\nlet previous = '';\n\nfunction appendNumber(num) {\n  if (current === '0') current = num;\n  else current += num;\n  updateDisplay();\n}\n\nfunction setOperator(op) {\n  previous = current;\n  operator = op;\n  current = '0';\n}\n\nfunction calculate() {\n  const a = parseFloat(previous);\n  const b = parseFloat(current);\n  let result = 0;\n  switch(operator) {\n    case '+': result = a + b; break;\n    case '-': result = a - b; break;\n    case '*': result = a * b; break;\n    case '/': result = a / b; break;\n  }\n  current = String(result);\n  updateDisplay();\n}`,
  },
  {
    id: "proj-2",
    title: "To-Do List",
    description: "Create a feature-rich to-do list with add, delete, mark complete, filter, and local storage persistence.",
    difficulty: "beginner",
    category: "Productivity",
    duration: "3 hours",
    skills: ["Arrays", "DOM Manipulation", "Events", "Local Storage", "CSS"],
    steps: [
      "Design the to-do list UI with input and list",
      "Implement add and delete functionality",
      "Add complete/incomplete toggle",
      "Implement filtering (All, Active, Completed)",
      "Add local storage persistence",
      "Add animations and polish the UI",
    ],
  },
  {
    id: "proj-3",
    title: "Digital Clock",
    description: "Build a beautiful digital clock with date display, stopwatch, and alarm functionality.",
    difficulty: "beginner",
    category: "Utility",
    duration: "2 hours",
    skills: ["Date Object", "setInterval", "DOM Manipulation", "CSS Animations"],
    steps: [
      "Create the clock display layout",
      "Implement time update with setInterval",
      "Add date display formatting",
      "Build a stopwatch with start/stop/reset",
      "Style with modern CSS and animations",
    ],
  },
  {
    id: "proj-4",
    title: "Counter App",
    description: "Build an interactive counter with increment, decrement, reset, custom step value, and history tracking.",
    difficulty: "beginner",
    category: "Interactive",
    duration: "1 hour",
    skills: ["State Management", "DOM Manipulation", "Events", "CSS Transitions"],
    steps: [
      "Create counter display and control buttons",
      "Implement increment and decrement logic",
      "Add custom step value input",
      "Track and display history",
      "Add animations for number changes",
    ],
  },
  {
    id: "proj-5",
    title: "Weather App",
    description: "Build a weather application that fetches real-time weather data and displays forecasts.",
    difficulty: "intermediate",
    category: "API Integration",
    duration: "5 hours",
    skills: ["Fetch API", "Async/Await", "JSON", "DOM Manipulation", "CSS Grid"],
    steps: [
      "Set up the weather UI layout",
      "Implement city search with fetch API",
      "Display current weather data",
      "Add 5-day forecast display",
      "Add loading states and error handling",
      "Implement geolocation support",
    ],
  },
  {
    id: "proj-6",
    title: "Quiz App",
    description: "Create an interactive quiz application with multiple choice, scoring, timer, and results.",
    difficulty: "intermediate",
    category: "Interactive",
    duration: "6 hours",
    skills: ["Arrays", "Objects", "Timers", "DOM Manipulation", "Events"],
    steps: [
      "Define quiz questions data structure",
      "Build the quiz UI with progress bar",
      "Implement question navigation",
      "Add scoring and timer system",
      "Create results page with review",
      "Add difficulty levels and categories",
    ],
  },
  {
    id: "proj-7",
    title: "Expense Tracker",
    description: "Build a personal finance tracker with income/expense management, charts, and categories.",
    difficulty: "intermediate",
    category: "Productivity",
    duration: "8 hours",
    skills: ["Objects", "Arrays", "Local Storage", "DOM Manipulation", "Charts"],
    steps: [
      "Design the expense tracker layout",
      "Implement add/edit/delete transactions",
      "Create category management",
      "Build monthly summary with charts",
      "Add filtering and search",
      "Implement data export functionality",
    ],
  },
  {
    id: "proj-8",
    title: "Notes App",
    description: "Create a rich notes application with markdown support, categories, search, and local storage.",
    difficulty: "intermediate",
    category: "Productivity",
    duration: "6 hours",
    skills: ["Strings", "Arrays", "Local Storage", "DOM Manipulation", "Events"],
    steps: [
      "Build the notes editor with toolbar",
      "Implement create, edit, delete notes",
      "Add markdown preview rendering",
      "Create category and tag system",
      "Add full-text search",
      "Implement dark/light theme toggle",
    ],
  },
  {
    id: "proj-9",
    title: "E-commerce Product Page",
    description: "Build a modern e-commerce product page with image gallery, cart, and checkout flow.",
    difficulty: "advanced",
    category: "Web Development",
    duration: "15 hours",
    skills: ["Components", "State Management", "Fetch API", "DOM", "CSS Grid/Flexbox"],
    steps: [
      "Design product layout and image gallery",
      "Implement product data fetching",
      "Build shopping cart with quantities",
      "Create checkout form with validation",
      "Add product filtering and search",
      "Implement responsive design",
    ],
  },
  {
    id: "proj-10",
    title: "Chat Application",
    description: "Build a real-time chat application with rooms, user management, and message history.",
    difficulty: "advanced",
    category: "Real-time",
    duration: "20 hours",
    skills: ["WebSocket", "Events", "DOM", "Async/Await", "Local Storage"],
    steps: [
      "Set up WebSocket connection",
      "Build chat room UI",
      "Implement message sending/receiving",
      "Add user presence indicators",
      "Create room management",
      "Add message history and search",
    ],
  },
  {
    id: "proj-11",
    title: "Social Media Dashboard",
    description: "Create a social media analytics dashboard with charts, stats, and user engagement metrics.",
    difficulty: "advanced",
    category: "Data Visualization",
    duration: "12 hours",
    skills: ["Chart.js/Recharts", "Fetch API", "CSS Grid", "Responsive Design"],
    steps: [
      "Design the dashboard layout",
      "Implement stat cards and KPIs",
      "Build interactive charts",
      "Add data filtering by date range",
      "Create user engagement metrics",
      "Add responsive sidebar navigation",
    ],
  },
  {
    id: "proj-12",
    title: "Full LMS Platform",
    description: "Build a complete Learning Management System with courses, progress tracking, and certificates.",
    difficulty: "expert",
    category: "Full-Stack",
    duration: "40+ hours",
    skills: ["All JavaScript Skills", "Architecture", "State Management", "API Design"],
    steps: [
      "Design the system architecture",
      "Build authentication system",
      "Create course management",
      "Implement progress tracking",
      "Build certificate generation",
      "Add analytics and reporting",
    ],
  },
];